# Difference between python list and numpy array

In [8]:
ls = [1,2,3,44,5,56,66,8]
ls[3:6] = 5

TypeError: can only assign an iterable

In [12]:
import numpy as np
arr = np.array([1,2,3,44,5,56,66,8])
arr[3:6] = 0
arr

array([ 1,  2,  3,  0,  0,  0, 66,  8])

In [14]:
arr_slice = arr[0:3]
print(arr_slice)
arr_slice[1:3] = 999
print(arr)

[1 2 3]
[  1 999 999   0   0   0  66   8]


In [28]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1][2])
print(arr_2d[1,2])
print(arr_2d)
print(arr_2d[:2,1:])

6
6
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [31]:
arr_3d = np.array([[[1,2,3],[4,5,6],[6,7,8]],[[9,10,11],[13,14,15],[16,17,18]]])
print(arr_3d[0])
print(arr_3d[1])
print(arr_3d[1,2,1]) 
print(arr_3d[-1,-1,-2])



[[1 2 3]
 [4 5 6]
 [6 7 8]]
[[ 9 10 11]
 [13 14 15]
 [16 17 18]]
17
17


In [32]:
print(arr_3d[1,:,1:])
print(arr_3d[1,1:,1:])

[[10 11]
 [14 15]
 [17 18]]
[[14 15]
 [17 18]]


In [36]:
print(arr_3d[-1,:,-3:-1])

[[ 9 10]
 [13 14]
 [16 17]]


In [37]:
print(arr_3d[1,:,:2])

[[ 9 10]
 [13 14]
 [16 17]]


In [52]:
names = np.array(['yawar','waqar','Ali','Ahmed','Luqman','Ali','waqar'])
data = np.random.randn(7,7)
data

array([[ 0.26740271,  0.36750796,  0.4158862 , -0.25280347,  1.03130523,
         0.25365031,  1.32782746],
       [-0.09948693,  2.27260649,  0.2380539 , -1.39583297, -0.49709366,
        -0.59160291, -2.13832081],
       [-1.37078977, -0.58180799,  0.56754325,  0.9284975 , -0.20999786,
        -0.52924074, -0.25260366],
       [-2.65839581, -0.81635256,  1.42086667,  0.58514014, -0.54145813,
        -2.55767376, -0.5985675 ],
       [ 2.04802249, -0.90213871,  0.15297324, -0.91875955,  0.17398908,
         1.9984766 ,  0.48164162],
       [-2.47393333,  1.30852006, -0.81074051, -0.94394287,  0.07613631,
         0.71064576,  0.10710384],
       [-1.49507049, -1.34232953,  0.12182859,  1.9904278 ,  1.68117323,
         0.47602405, -0.81961469]])

# boolean indexing


In [54]:
data[names == 'yawar']

array([[ 0.26740271,  0.36750796,  0.4158862 , -0.25280347,  1.03130523,
         0.25365031,  1.32782746]])

In [61]:
data[(names == 'waqar') | (names == 'yawar')]

array([[ 0.26740271,  0.36750796,  0.4158862 , -0.25280347,  1.03130523,
         0.25365031,  1.32782746],
       [-0.09948693,  2.27260649,  0.2380539 , -1.39583297, -0.49709366,
        -0.59160291, -2.13832081],
       [-1.49507049, -1.34232953,  0.12182859,  1.9904278 ,  1.68117323,
         0.47602405, -0.81961469]])

In [60]:
data[(names == 'waqar') | (names == 'yawar'),:2]

array([[ 0.26740271,  0.36750796],
       [-0.09948693,  2.27260649],
       [-1.49507049, -1.34232953]])

In [63]:
data[~(names == 'waqar'),:4]

array([[ 0.26740271,  0.36750796,  0.4158862 , -0.25280347],
       [-1.37078977, -0.58180799,  0.56754325,  0.9284975 ],
       [-2.65839581, -0.81635256,  1.42086667,  0.58514014],
       [ 2.04802249, -0.90213871,  0.15297324, -0.91875955],
       [-2.47393333,  1.30852006, -0.81074051, -0.94394287]])

In [69]:
mask = (names == 'Ali') | (names == 'waqar')
print(data[mask])
print(data[~mask])


[[-0.09948693  2.27260649  0.2380539  -1.39583297 -0.49709366 -0.59160291
  -2.13832081]
 [-1.37078977 -0.58180799  0.56754325  0.9284975  -0.20999786 -0.52924074
  -0.25260366]
 [-2.47393333  1.30852006 -0.81074051 -0.94394287  0.07613631  0.71064576
   0.10710384]
 [-1.49507049 -1.34232953  0.12182859  1.9904278   1.68117323  0.47602405
  -0.81961469]]
[[ 0.26740271  0.36750796  0.4158862  -0.25280347  1.03130523  0.25365031
   1.32782746]
 [-2.65839581 -0.81635256  1.42086667  0.58514014 -0.54145813 -2.55767376
  -0.5985675 ]
 [ 2.04802249 -0.90213871  0.15297324 -0.91875955  0.17398908  1.9984766
   0.48164162]]


# Fancy Indexing

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays

In [78]:
arry = np.random.randn(4,4)


In [86]:
for index, _ in np.ndenumerate(arry):
    print(index)
    


(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(2, 0)
(2, 1)
(2, 2)
(2, 3)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


In [87]:
arry

array([[-0.53822095, -1.36098452,  1.88056641,  0.67613373],
       [ 0.4983888 ,  2.05674216, -1.70102653, -0.76247021],
       [ 0.98653373, -0.50948141, -0.86596004,  0.23876864],
       [-1.59325033, -1.08375919, -0.40674594, -0.25897772]])

In [89]:
arry[[2,1,0,3]]

array([[ 0.98653373, -0.50948141, -0.86596004,  0.23876864],
       [ 0.4983888 ,  2.05674216, -1.70102653, -0.76247021],
       [-0.53822095, -1.36098452,  1.88056641,  0.67613373],
       [-1.59325033, -1.08375919, -0.40674594, -0.25897772]])

In [90]:
arry[[-2,-3,-1,-4]]

array([[ 0.98653373, -0.50948141, -0.86596004,  0.23876864],
       [ 0.4983888 ,  2.05674216, -1.70102653, -0.76247021],
       [-1.59325033, -1.08375919, -0.40674594, -0.25897772],
       [-0.53822095, -1.36098452,  1.88056641,  0.67613373]])

In [92]:
arry[[0,1,2,3],[0,1,2,3]]

array([-0.53822095,  2.05674216, -0.86596004, -0.25897772])