In [1]:
import numpy as np
nums = [[1,2,3],[4,5,6],[7,8,9]]
arr_of_nums = np.array(nums,dtype = np.int8)
print(arr_of_nums)
print(arr_of_nums.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
int8


# Changing datatypes of arrays 

In [5]:
arr_typ_cov = arr_of_nums.astype(np.float64)
print(arr_typ_cov.dtype)
arr_typ_cov[0,1]=3.4
print(arr_typ_cov)
print(arr_of_nums)

float64
[[1.  3.4 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_typ_cov = arr_of_nums.astype

In [9]:
nums = [[3.5,0,0],[2.4,0,5],[2,0,6]]
arr = np.array(nums, dtype = np.int32)
print(arr)

[[3 0 0]
 [2 0 5]
 [2 0 6]]


In [6]:
empty = np.zeros??


In [12]:
empty = np.zeros((3,3),dtype = np.int32)
print(empty)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Comparing two arrays

In [14]:
print(arr > empty)
arr[arr > empty]


[[ True False False]
 [ True False  True]
 [ True False  True]]


array([3, 2, 5, 2, 6], dtype=int32)

# Basic Indexing and slicing in numpy

An important first dis‐tinction from Python’s built-in lists is that array slices are views on the original array.This means that the data is not copied, and any modifications to the view will be
reflected in the source array.

In [37]:
list_of_nums = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list_of_nums, dtype = np.int32)
print(arr)
slice_of_arr = arr[:2]
slice_of_arr[0][1] = 3
print(arr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3 3]
 [4 5 6]
 [7 8 9]]


other array programming languages that copy data more eagerly. As NumPy has been
designed to be able to work with very large arrays, you could imagine performance
and memory problems if NumPy insisted on always copying data.
If you want a copy of a slice of an ndarray instead of a view, you
will need to explicitly copy the array—for example,
arr[5:8].copy() . Now you can compare below and above code how you can copy arrays in numpy

In [39]:
arr = np.arange(9).reshape(3,3)
print(arr)
slice_arr = arr[:2].copy()
slice_arr[0][1] = 3
print(arr)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
print(arr[2,2])
print(arr[2][2])


8
8


Creating a three dimensional array with (two matrices of order 2 X 3). Create a temporary variable
to hold previous values of array and then change the original array. After changing vlaues of array restore it to its original state

In [51]:
arr = np.ones(12).reshape(2,2,3)
print(arr)
old_values_of_arr = arr[0].copy()
arr[0] = 2
print(arr)
arr[0] = old_values_of_arr
print(arr)



[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[2. 2. 2.]
  [2. 2. 2.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [57]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
arr[1,1]
new_order_arr = arr[1, :1,:2]
print(new_order_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[7 8]]


In [63]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = np.float32)
print(arr_2d)
arr_2d_slice = arr_2d[:3,:2]
print(arr_2d_slice)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2.]
 [4. 5.]
 [7. 8.]]


In [65]:
arr_2d_slice[:] = 0
print(arr_2d)

[[0. 0. 3.]
 [0. 0. 6.]
 [0. 0. 9.]]
