# Fancy Indexing

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [1]:
import numpy as np
arr = np.random.randn(8,4)
print(arr)

[[-1.0345352   0.65571173  0.21146731 -1.40680171]
 [-0.46330342 -0.2717517  -0.2468531   0.11388579]
 [ 0.27189205  1.0340687  -2.61094553 -0.32416183]
 [-1.35526925 -0.19341693 -0.9423168   0.18216037]
 [ 2.87850164 -0.18591028  1.15662657  0.52410038]
 [ 0.12131264 -1.34385567 -0.12754586 -0.08272747]
 [-0.00954006  1.18501759 -1.02422505 -1.38641869]
 [-0.90904219  0.41245436  0.40802515  0.89680366]]


In [6]:
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


To select out a subset of the rows in a particular order, you can simply pass a list or
ndarray of integers specifying the desired order. They are just row indexes


In [7]:
arr[[0,3,7]]

array_of_nums = np.array([[5,6,7],[2,36,49],[76,45,67],[1,34,67]])
array_of_nums[[2,3,0,1]]
array_of_nums[[-3,-4]]
print(array_of_nums)
array_of_nums[[0,1,2],[0,1,2]]




[[ 5  6  7]
 [ 2 36 49]
 [76 45 67]
 [ 1 34 67]]


array([ 5, 36, 67])

In [17]:
arr[[-3,-5,-8]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

Passing multiple index arrays does something slightly different; it selects a one-
dimensional array of elements corresponding to each tuple of indices

Here the elements (1, 0), (5, 3), (7, 1) , and (2, 2) were selected. Regardless of
how many dimensions the array has (here, only 2), the result of fancy indexing is
always one-dimensional.

In [25]:
arr_1 = np.arange(32).reshape(8,4)
print(arr_1)
arr_1[[1,5,7,2],[0,3,1,2]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

Keep in mind that fancy indexing, unlike slicing, always copies the data into a new
array.

# Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping that similarly returns a view on the under‐
lying data without copying anything. Arrays have the transpose method and also the
special T attribute

In [31]:
arr_2 = np.arange(15).reshape(3,5)
print(arr_2)
arr_2.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In mathematics, the Frobenius inner product is a binary operation that takes two matrices and returns a number. When doing matrix computations, you may do this very often—for example, when
computing the inner matrix product using np.dot :
inner product also known as dot product
x . y = x(transpose) * y (matrix)
https://web.auburn.edu/holmerr/2660/Textbook/innerproduct-print.pdf


In [41]:
arr_3 = np.arange(3).reshape(3,1)
arr_4 = np.arange(3).reshape(3,1)
transpose_arr3 = arr_3.T
print(transpose_arr3)
print(arr_4)

inner_product = np.dot(transpose_arr3, arr_4)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [40]:
inner_product

array([[5]])

# Universal Functions: Fast Element-Wise Array Functions

In [44]:
arr_5 = np.arange(10).reshape(1,10)
arr_5

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [45]:
np.sqrt(arr_5)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [47]:
np.exp(arr_5)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03]])

Here, numpy.maximum computed the element-wise maximum of the elements in x and y.


In [51]:
arr_6 = np.random.randn(8)
arr_7 = np.random.randn(8)
print(arr_6)
print(arr_7)

[ 1.26936172  1.09464873  0.46383581  0.09326455 -1.73627663 -1.30273759
 -0.79719552 -0.46084759]
[-2.20817116 -0.53084299 -0.65723344 -0.9816164   0.95828524 -1.58279795
 -1.4284789   1.57458646]


In [52]:
np.maximum(arr_6,arr_7)

array([ 1.26936172,  1.09464873,  0.46383581,  0.09326455,  0.95828524,
       -1.30273759, -0.79719552,  1.57458646])

To get remainder and whole out of a number

In [56]:
arr_8 = np.array([1.2,3.45,7.32,34.77,96.321])
arr_8

array([ 1.2  ,  3.45 ,  7.32 , 34.77 , 96.321])

In [60]:
remainder,whole_num = np.modf(arr_8)

In [61]:
remainder

array([0.2  , 0.45 , 0.32 , 0.77 , 0.321])

In [62]:
whole_num

array([ 1.,  3.,  7., 34., 96.])

In [67]:
whole_num.dtype

dtype('float64')