# Psedo Random Number

In [3]:
import numpy as np
np.random.normal( size = (3,3))

array([[-1.88646926,  1.95592546, -0.50668796],
       [ 1.13818286,  0.22841576, -0.45215275],
       [ 0.40408607, -1.03567734,  0.34086557]])

# Reshaping Array

In [6]:
arr = np.random.randn(4,5)
arr

array([[ 2.31782838,  0.08918769,  0.1192582 ,  0.59351895, -0.00287283],
       [-0.47158318,  0.24025718,  0.09727694, -0.32112888,  2.6898947 ],
       [ 0.13959465,  0.26059812,  0.26703633,  0.1780239 , -0.44482554],
       [ 0.57227074,  0.30595346,  0.38155307, -0.4017773 , -0.84821948]])

In [9]:
arr.reshape((2,2,5),order = 'F')

array([[[ 2.31782838,  0.08918769,  0.1192582 ,  0.59351895,
         -0.00287283],
        [ 0.13959465,  0.26059812,  0.26703633,  0.1780239 ,
         -0.44482554]],

       [[-0.47158318,  0.24025718,  0.09727694, -0.32112888,
          2.6898947 ],
        [ 0.57227074,  0.30595346,  0.38155307, -0.4017773 ,
         -0.84821948]]])

# Concatenation

In [16]:
arr_1 = np.arange(1,10).reshape(3,3)
arr_2 = np.arange(10,19).reshape(3,3)
print(arr_1)
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [20]:
np.concatenate((arr_1, arr_2), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [21]:
np.concatenate((arr_1,arr_2), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

Similar functions for concatenation

In [22]:
np.hstack((arr_1,arr_2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [24]:
np.vstack((arr_1,arr_2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# Spliting Arrays

In [26]:
arr_3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr_3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
np.split(arr_3, [2], axis = 1)

[array([[ 1,  2],
        [ 6,  7],
        [11, 12]]),
 array([[ 3,  4,  5],
        [ 8,  9, 10],
        [13, 14, 15]])]

In [30]:
np.split(arr_3, [1,2], axis = 0)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]])]

# Tile And Repeat

In [32]:
arr_4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.repeat(arr_4, 2, axis = 1)

array([[1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6],
       [7, 7, 8, 8, 9, 9]])

In [35]:
np.repeat(arr_4, 3, axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9]])

In [37]:
np.tile(arr_4, 2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])