# Unique and Other Set Logic

In [1]:
import numpy as np

In [5]:
names = np.array(['bob','john','micky','bob','micky','will','steve','will'])
np.unique(names)


array(['bob', 'john', 'micky', 'steve', 'will'], dtype='<U5')

Contrast np.unique with the pure Python alternative:

In [7]:
set(names)

['bob', 'john', 'micky', 'steve', 'will']

Another function, np.in1d , tests membership of the values in one array in another,
returning a boolean array:

In [8]:
names_to_check =np.array(['bob','steve','will'])
np.in1d(names_to_check,names)

array([ True,  True,  True])

# Mathematical and Statistical Methods

In [13]:
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(np.mean(matrix))
print(np.cumsum(matrix, axis = 0))
print(np.cumprod(matrix, axis = 1))

5.0
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


Methods for Boolean Arrays
To check how many true values are their
To check if any value is true
To check whether all values are true

In [20]:
bool_arr = np.array([True,False,False,True,False,True,True])
print(np.sum(bool_arr))
print(np.any(bool_arr))
print(np.all(bool_arr))

4
True
False


In [26]:
arr = np.array([[4,5,2,6],[1,8,3,0],[7,3,1,4]]).reshape(3,4)
print(arr)

[[4 5 2 6]
 [1 8 3 0]
 [7 3 1 4]]


In [27]:
np.sort(arr, axis = 1)

array([[2, 4, 5, 6],
       [0, 1, 3, 8],
       [1, 3, 4, 7]])

In [28]:
np.sort(arr, axis = 0)

array([[1, 3, 1, 0],
       [4, 5, 2, 4],
       [7, 8, 3, 6]])

Remember when you are using np.function() and give it to array it dosen't changes
the original array values but if you want to change the original array you should
use these functions as arr.function(axis)

In [31]:
arr.sort(axis = 0)
arr


array([[1, 3, 1, 0],
       [4, 5, 2, 4],
       [7, 8, 3, 6]])