# File Input and Output with Arrays

In [4]:
import numpy as np

In [6]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
np.save('matrix',arr)

In [17]:
np.load('matrix.npy')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# To save and load more than one arrays using keyword arguments

In [20]:
arr_1 = np.array([[3,4,5,6],[5,6,7,2],[1,9,0,2]])
arr_2 = np.array([[3,3,5,2],[5,1,7,4],[1,7,0,7]])
np.savez('multiple_arrays', a = arr_1, b = arr_2)


In [25]:
data = np.load('multiple_arrays.npz')
data['b']



array([[3, 3, 5, 2],
       [5, 1, 7, 4],
       [1, 7, 0, 7]])