# File Input and Output with Arrays

np.save and np.load are the two workhorse functions for efficiently saving and load‐
ing array data on disk

In [2]:
import numpy as np
arr = np.arange(10)
np.save("some_arr",arr)

Now loading array data

In [5]:
np.load("some_arr.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You save multiple arrays in an uncompressed archive using np.savez and passing the
arrays as keyword arguments

In [7]:
arr_1 = np.arange(10)
arr_2 = np.arange(10,20)
np.savez("two_arrays", a = arr_1, b = arr_2)


When loading an .npz file, you get back a dict-like object that loads the individual
arrays lazily

In [12]:
two_arrays = np.load("two_arrays.npz")
print(two_arrays['a'])
print(two_arrays['b'])

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


If your data compresses well, you may wish to use numpy.savez_compressed instead

In [15]:
np.savez_compressed("another_two_compressed", a = arr_1, b = arr_2)

In [17]:
another_two = np.load("another_two_compressed.npz")
another_two['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Linear Algebra

Matrix multiplication

In [20]:
arr_3 = np.array([[2,3,1],[1,4,5],[4,6,2]])
arr_4 = np.array([[3,2,6],[3,7,2],[9,6,2]])
np.dot(arr_3,arr_4)

array([[24, 31, 20],
       [60, 60, 24],
       [48, 62, 40]])

numpy.linalg has a standard set of matrix decompositions and things like inverse
and determinant. These are implemented under the hood via the same industry-
standard linear algebra libraries used in other languages like MATLAB and R, such as
BLAS, LAPACK, or possibly (depending on your NumPy build) the proprietary Intel
MKL (Math Kernel Library):

In [23]:
from numpy.linalg import inv,qr
arr_5 =np.array([[1,2],[3,4]])
print(arr_5)
inv(arr_5)

[[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])