In [21]:
import numpy as np
arr = np.arange(1,100,1)
xs, ys = np.meshgrid(arr,arr)
z = np.sqrt(xs**2 + ys**2)
z


array([[  1.41421356,   2.23606798,   3.16227766, ...,  97.0051545 ,
         98.00510191,  99.00505038],
       [  2.23606798,   2.82842712,   3.60555128, ...,  97.02061637,
         98.02040604,  99.02019996],
       [  3.16227766,   3.60555128,   4.24264069, ...,  97.04638066,
         98.04590761,  99.04544412],
       ...,
       [ 97.0051545 ,  97.02061637,  97.04638066, ..., 137.17871555,
        137.88763541, 138.6001443 ],
       [ 98.00510191,  98.02040604,  98.04590761, ..., 137.88763541,
        138.59292911, 139.30183057],
       [ 99.00505038,  99.02019996,  99.04544412, ..., 138.6001443 ,
        139.30183057, 140.00714267]])

# Mathematical and Statistical Methods

In [24]:
arr_1 = np.random.randn(5,4)
print(arr_1)

[[-0.81243321 -0.84814137  2.44399362 -1.07155025]
 [ 0.41706112 -1.90865846 -0.69350571 -0.92284377]
 [ 2.01616337  1.78890854 -1.35105617  0.25128449]
 [-0.6942556  -0.50408314 -0.01628782 -0.25634889]
 [ 0.10886777 -0.11964872 -0.07139799  0.58380787]]


In [28]:
print(np.sum(arr_1))
print(np.mean(arr_1))



-1.6601243280452591
-0.08300621640226295


To understand axis given and sum or mean

In [30]:
arr = np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

0 axis is for columns and 1 axis is for rows


In [40]:
print(arr.sum(axis = 1))
print(arr.sum(axis = 0))
print(arr.mean(axis = 0))
print(arr.mean(axis = 1))

[ 3 12 21]
[ 9 12 15]
[3. 4. 5.]
[1. 4. 7.]


For example, the cumulative sums of the sequence {a,b,c,...}, are a, a+b, a+b+c, .... 

In [43]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [44]:
arr.cumsum(axis = 1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

# Methods for Boolean Arrays

In [47]:
arr_3 = np.random.randn(3,4)
(arr_3 > 0).sum()

8

any function tests whether one or more values in an array is True , while all function checks if every
value is True :

In [48]:
(arr_3 > 0).any()

True

In [49]:
(arr_3 > 0).all()

False

These methods also work with non-boolean arrays, where non-zero elements evaluate to True. Given below example

In [50]:
arr_3.any()

True

# Sorting

In [58]:
arr_4 = np.array([3,5,1,7,2,4,9,8,0])
print(arr_4)

[3 5 1 7 2 4 9 8 0]


In [62]:
arr_4.sort()
arr_4


array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [64]:
arr_5 = np.array([[4,8,1],[6,9,3],[8,0,2]])
print(arr_5)

[[4 8 1]
 [6 9 3]
 [8 0 2]]


In [66]:
arr_5.sort(axis = 1)
arr_5

array([[1, 4, 8],
       [3, 6, 9],
       [0, 2, 8]])

In [67]:
arr_5.sort(axis = 0)
arr_5

array([[0, 2, 8],
       [1, 4, 8],
       [3, 6, 9]])

# Unique and Other Set Logic

In [70]:
arr = np.array(['waqar','yawar','waqar','nida','yawar','tauqeer','sakeena','tauqeer'])
np.unique(arr)

array(['nida', 'sakeena', 'tauqeer', 'waqar', 'yawar'], dtype='<U7')

In [71]:
arr = np.array([1,2,3,4,2,3,5,6,7,2,4,6,4,2])
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

np.in1d , tests membership of the values in one array in another,
returning a boolean array:



In [72]:
arr_6 = np.array([1,2,3,4,5,6,7,8])
arr_7 = np.array([2,3,4,0,6])
np.in1d(arr_6, arr_7)

array([False,  True,  True,  True, False,  True, False, False])