In [5]:
import numpy as np
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
zeros_array = np.zeros_like(arr)
zeros_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
arr_of_fives = np.full((3,3),5)
arr_of_fives

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
arr_2 = np.arange(6).reshape(2,3)
arr_of_nines = np.full_like(arr_2, 9)
arr_of_nines

array([[9, 9, 9],
       [9, 9, 9]])

In [23]:
identity_matrix = np.identity(3)
id_mat_lowerdiagonal_1 = np.eye(3,3,-1)

print(identity_matrix)
print(id_mat_lowerdiagonal_1)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [25]:
identity_matrix.dtype

dtype('float64')

In [27]:
arr_4 = np.arange(5,10)
arr_4

array([5, 6, 7, 8, 9])

In [28]:
arr_4[1:4]

array([6, 7, 8])

In [29]:
arr[[2,0,1]]

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [30]:
arr[[-2,-3,-1]]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [31]:
arr[[0,1,2],[0,1,2]]

array([0, 4, 8])

In [50]:
arr_5 = np.arange(5,14).reshape(3,3)
arr_6 = np.arange(0,9).reshape(3,3)
print(arr_5)
print(arr_6)


[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
np.dot(arr_5.T,arr_6)

array([[ 90, 114, 138],
       [ 99, 126, 153],
       [108, 138, 168]])

In [45]:
(arr_5.T) @ arr_6

array([[ 90, 114, 138],
       [ 99, 126, 153],
       [108, 138, 168]])

In [46]:
np.maximum(arr_5,arr_6)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [48]:
arr_6 = np.arange(1,10)
arr_7 = np.arange(10,20)

np.meshgrid(arr_6, arr_7)

[array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 10, 10, 10, 10, 10, 10, 10, 10],
        [11, 11, 11, 11, 11, 11, 11, 11, 11],
        [12, 12, 12, 12, 12, 12, 12, 12, 12],
        [13, 13, 13, 13, 13, 13, 13, 13, 13],
        [14, 14, 14, 14, 14, 14, 14, 14, 14],
        [15, 15, 15, 15, 15, 15, 15, 15, 15],
        [16, 16, 16, 16, 16, 16, 16, 16, 16],
        [17, 17, 17, 17, 17, 17, 17, 17, 17],
        [18, 18, 18, 18, 18, 18, 18, 18, 18],
        [19, 19, 19, 19, 19, 19, 19, 19, 19]])]

In [51]:
arr_6.sum(axis = 1)

array([ 3, 12, 21])

In [53]:
print(arr_6)
arr_6.cumsum(axis = 0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [56]:
arr_6.sort(0)
arr_6.sort(1)

In [62]:
arr_7 = np.array([[5,3,77],[32,45,221],[2,9,1]])
print(arr_7)
arr_7.sort(0)
print(arr_7)


[[  5   3  77]
 [ 32  45 221]
 [  2   9   1]]
[[  2   3   1]
 [  5   9  77]
 [ 32  45 221]]


In [63]:
arr_1 = np.arange(10)
arr_2 = np.array([5,8,11,44,33,2,9,10,34,3])
np.in1d(arr_2,arr_1)

array([ True,  True, False, False, False,  True,  True, False, False,
        True])